name: 'Set up steps'
description: 'Steps to set up node, yarn and install dependencies'

inputs:
  npm_token:
    description: 'NPM token to install dependencies from private registry'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys:
          ${{ runner.os }}-yarn-

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}
