name: Lint and Typescript

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ_ONLY }}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint_typescript:
    name: Lint and Typescript checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      
      - name: Set up steps
        uses: ./.github/actions/setup-steps
        with:
          npm_token: ${{ secrets.NPM_TOKEN_READ_ONLY }}

      - name: Run styles lint
        run: yarn lint:styles:ci

      - name: Run lint
        run: yarn lint:ci

      - name: Type checking
        run: yarn types:check
