name: Secrets Scan

on:
  workflow_call:

jobs:
  specs:
    name: Secrets scan
    runs-on: squad-growth-ubuntu2204-x64-standard
    permissions: write-all
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the secrets from GSM
        id: secrets_manager
        uses: toptal/actions/gsm-secrets@v1.0.2
        with:
          workload_identity_provider: projects/858873486241/locations/global/workloadIdentityPools/gha-pool/providers/github-com
          service_account: gha-keycodes@toptal-ci.iam.gserviceaccount.com
          secrets_name: |-
            SLACK_BOT_TOKEN:toptal-ci/SLACK_BOT_TOKEN

      - name: Parse secrets
        id: parse_secrets
        uses: toptal/actions/expose-json-outputs@v1.0.2
        with:
          json: ${{ steps.secrets_manager.outputs.secrets }}

      - name: Secrets Scan
        uses: toptal/actions/secret-scanning-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          full-scan: true
          slack-channel: -marketing-tools-2-releases
          slack-token: ${{ steps.parse_secrets.outputs.SLACK_BOT_TOKEN }}

